Exercise 1:Loading Data with pandas

In [2]:
import numpy as np
import pandas as pd
import pickle

In [3]:
myData = pd.read_csv("C:/Users/User/Downloads/archive/ClassicDisco.csv")
myData.head(10)

,Track,Artist,Album,Year,Duration,Time_Signature,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Popularity
0,Boogie Oogie Oogie,A Taste Of Honey,A Taste Of Honey,1978,245173,4,0.797,0.548,2,-9.228,0,0.0492,0.0401,0.000010,0.0994,0.868,123.686,53
1,Disco Dancin' - 2004 - Remastered,A Taste Of Honey,A Taste Of Honey,1978,210493,4,0.751,0.570,2,-11.645,1,0.0813,0.3710,0.000020,0.1230,0.770,103.408,11
2,Distant,A Taste Of Honey,A Taste Of Honey,1978,260053,4,0.468,0.512,2,-10.187,1,0.1380,0.7820,0.000020,0.2020,0.714,163.400,13
3,Do It Good,A Taste Of Honey,Another Taste (Expanded Edition),1978,342826,4,0.699,0.740,3,-8.625,0,0.0289,0.0714,0.000002,0.1650,0.889,104.168,17
4,If We Loved,A Taste Of Honey,A Taste Of Honey,1978,266200,4,0.463,0.459,6,-11.600,1,0.0296,0.7640,0.000003,0.1580,0.300,129.267,13
5,Rescue Me - Remastered,A Taste Of Honey,Twice As Sweet,1978,203000,4,0.806,0.741,5,-7.351,0,0.0494,0.2250,0.000052,0.0568,0.881,106.817,35
6,Sky High,A Taste Of Honey,A Taste Of Honey,1978,307040,4,0.397,0.603,0,-12.278,0,0.0732,0.6770,0.000002,0.2290,0.382,93.534,12
7,This Love Of Ours,A Taste Of Honey,A Taste Of Honey,1978,213266,4,0.514,0.542,9,-10.298,1,0.0277,0.6150,0.000169,0.1230,0.393,107.687,13
8,World Spin,A Taste Of Honey,A Taste Of Honey,1978,242000,4,0.642,0.465,2,-11.385,1,0.0283,0.2100,0.010200,0.1200,0.597,99.375,20
9,Chiquitita,ABBA,Voulez-Vous,1978,326320,4,0.500,0.554,9,-8.108,1,0.0354,0.7340,0.000004,0.3120,0.372,84.229,72

In [4]:
myData.tail()

,Track,Artist,Album,Year,Duration,Time_Signature,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Popularity
719,Lady America,Voyage,"Twelve Inch Classics from the 70s, Vol. 2",1979,407800,4,0.649,0.840,5,-7.713,1,0.0411,0.000681,0.006580,0.3750,0.921,128.020,23
720,Let's Fly Away,Voyage,Fly Away,1979,306818,4,0.709,0.854,8,-4.750,1,0.0348,0.050600,0.000055,0.6240,0.900,129.258,15
721,Scotch Machine,Voyage,Voyage,1979,208200,4,0.633,0.901,10,-10.248,1,0.0325,0.000343,0.909000,0.0533,0.862,129.173,20
722,Souvenirs,Voyage,Fly Away,1979,390567,4,0.633,0.970,5,-4.153,1,0.0380,0.000667,0.202000,0.3960,0.757,127.776,29
723,"Tahiti, Tahiti…",Voyage,Fly Away,1979,299510,4,0.672,0.972,2,-4.929,1,0.1390,0.004250,0.000009,0.1010,0.815,127.591,24

In [5]:
myData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 724 entries, 0 to 723
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Track             724 non-null    object
 1   Artist            724 non-null    object
 2   Album             724 non-null    object
 3   Year              724 non-null    int64
 4   Duration          724 non-null    int64
 5   Time_Signature    724 non-null    int64
 6   Danceability      724 non-null    float64
 7   Energy            724 non-null    float64
 8   Key               724 non-null    int64
 9   Loudness          724 non-null    float64
 10  Mode              724 non-null    int64
 11  Speechiness       724 non-null    float64
 12  Acousticness      724 non-null    float64
 13  Instrumentalness  724 non-null    float64
 14  Liveness          724 non-null    float64
 15  Valence           724 non-null    float64
 16  Tempo             724 non-null    float64
 17  Popularity        724 non-null    int64
dtypes: float64(9), int64(6), object(3)
memory usage: 101.9+ KB

In [46]:
missing_values = myData.isnull()
print("Missing values in each column :")
print(missing_values.head())

Missing values in each column :
   Track  Artist  Album   Year  Duration  Time_Signature  Danceability  \
0  False   False  False  False     False           False         False
1  False   False  False  False     False           False         False
2  False   False  False  False     False           False         False
3  False   False  False  False     False           False         False
4  False   False  False  False     False           False         False

   Energy    Key  Loudness   Mode  Speechiness  Acousticness  \
0   False  False     False  False        False         False
1   False  False     False  False        False         False
2   False  False     False  False        False         False
3   False  False     False  False        False         False
4   False  False     False  False        False         False

   Instrumentalness  Liveness  Valence  Tempo  Popularity
0             False     False    False  False       False
1             False     False    False  False       False
2             False     False    False  False       False
3             False     False    False  False       False
4             False     False    False  False       False

In [48]:
missingvalues_cnt = myData.isnull().sum()
print("The count of missing values: ")
print(missingvalues_cnt)

The count of missing values:
Track               0
Artist              0
Album               0
Year                0
Duration            0
Time_Signature      0
Danceability        0
Energy              0
Key                 0
Loudness            0
Mode                0
Speechiness         0
Acousticness        0
Instrumentalness    0
Liveness            0
Valence             0
Tempo               0
Popularity          0
dtype: int64

In [9]:
Data_types = myData.dtypes
print("Data types of each column :")
print(Data_types)

Data types of each column :
Track                object
Artist               object
Album                object
Year                  int64
Duration              int64
Time_Signature        int64
Danceability        float64
Energy              float64
Key                   int64
Loudness            float64
Mode                  int64
Speechiness         float64
Acousticness        float64
Instrumentalness    float64
Liveness            float64
Valence             float64
Tempo               float64
Popularity            int64
dtype: object

Exercise 2:Handling Missing Data

In [11]:
Data = pd.read_csv("C:/Users/User/Downloads/melb_data.csv/melb_data.csv")
Data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [12]:
Data_dropna = Data.dropna()
print("Dataframe after dropping rows with missing values :")
print(Data_dropna)

Dataframe after dropping rows with missing values :
             Suburb          Address  Rooms Type      Price Method  \
1        Abbotsford  25 Bloomburg St      2    h  1035000.0      S
2        Abbotsford     5 Charles St      3    h  1465000.0     SP
4        Abbotsford      55a Park St      4    h  1600000.0     VB
6        Abbotsford     124 Yarra St      3    h  1876000.0      S
7        Abbotsford    98 Charles St      2    h  1636000.0      S
...             ...              ...    ...  ...        ...    ...
12205    Whittlesea    30 Sherwin St      3    h   601000.0      S
12206  Williamstown      75 Cecil St      3    h  1050000.0     VB
12207  Williamstown    2/29 Dover Rd      1    u   385000.0     SP
12209       Windsor  201/152 Peel St      2    u   560000.0     PI
12212    Yarraville  54 Pentland Pde      6    h  2450000.0     VB

             SellerG        Date  Distance  Postcode  ...  Bathroom  Car  \
1             Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0
2             Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0
4             Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0
6             Nelson   7/05/2016       2.5    3067.0  ...       2.0  0.0
7             Nelson   8/10/2016       2.5    3067.0  ...       1.0  2.0
...              ...         ...       ...       ...  ...       ...  ...
12205            Ray  29/07/2017      35.5    3757.0  ...       2.0  1.0
12206       Williams  29/07/2017       6.8    3016.0  ...       1.0  0.0
12207       Williams  29/07/2017       6.8    3016.0  ...       1.0  1.0
12209  hockingstuart  29/07/2017       4.6    3181.0  ...       1.0  1.0
12212        Village  29/07/2017       6.3    3013.0  ...       3.0  2.0

       Landsize  BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
1         156.0         79.00     1900.0        Yarra -37.80790   144.99340
2         134.0        150.00     1900.0        Yarra -37.80930   144.99440
4         120.0        142.00     2014.0        Yarra -37.80720   144.99410
6         245.0        210.00     1910.0        Yarra -37.80240   144.99930
7         256.0        107.00     1890.0        Yarra -37.80600   144.99540
...         ...           ...        ...          ...       ...         ...
12205     972.0        149.00     1996.0   Whittlesea -37.51232   145.13282
12206     179.0        115.00     1890.0  Hobsons Bay -37.86558   144.90474
12207       0.0         35.64     1967.0  Hobsons Bay -37.85588   144.89936
12209       0.0         61.60     2012.0  Stonnington -37.85581   144.99025
12212    1087.0        388.50     1920.0  Maribyrnong -37.81038   144.89389

                  Regionname Propertycount
1      Northern Metropolitan        4019.0
2      Northern Metropolitan        4019.0
4      Northern Metropolitan        4019.0
6      Northern Metropolitan        4019.0
7      Northern Metropolitan        4019.0
...                      ...           ...
12205      Northern Victoria        2170.0
12206   Western Metropolitan        6380.0
12207   Western Metropolitan        6380.0
12209  Southern Metropolitan        4380.0
12212   Western Metropolitan        6543.0

[6196 rows x 21 columns]

In [13]:
mean_year = Data['YearBuilt'].mean()
Data_mean_fill = Data.fillna({'YearBuilt':mean_year})
print("Dataframe after filling missing 'YearBuilt' with mean:")
print(Data_mean_fill)

Dataframe after filling missing 'YearBuilt' with mean:
              Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S
2         Abbotsford      5 Charles St      3    h  1465000.0     SP
3         Abbotsford  40 Federation La      3    h   850000.0     PI
4         Abbotsford       55a Park St      4    h  1600000.0     VB
...              ...               ...    ...  ...        ...    ...
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP
13577   Williamstown       83 Power St      3    h  1170000.0      S
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0
...         ...         ...       ...       ...  ...       ...  ...       ...
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0

       BuildingArea    YearBuilt  CouncilArea Lattitude  Longtitude  \
0               NaN  1964.684217        Yarra -37.79960   144.99840
1              79.0  1900.000000        Yarra -37.80790   144.99340
2             150.0  1900.000000        Yarra -37.80930   144.99440
3               NaN  1964.684217        Yarra -37.79690   144.99690
4             142.0  2014.000000        Yarra -37.80720   144.99410
...             ...          ...          ...       ...         ...
13575           NaN  1981.000000          NaN -37.90562   145.16761
13576         133.0  1995.000000          NaN -37.85927   144.87904
13577           NaN  1997.000000          NaN -37.85274   144.88738
13578         157.0  1920.000000          NaN -37.85908   144.89299
13579         112.0  1920.000000          NaN -37.81188   144.88449

                       Regionname Propertycount
0           Northern Metropolitan        4019.0
1           Northern Metropolitan        4019.0
2           Northern Metropolitan        4019.0
3           Northern Metropolitan        4019.0
4           Northern Metropolitan        4019.0
...                           ...           ...
13575  South-Eastern Metropolitan        7392.0
13576        Western Metropolitan        6380.0
13577        Western Metropolitan        6380.0
13578        Western Metropolitan        6380.0
13579        Western Metropolitan        6543.0

[13580 rows x 21 columns]

In [14]:
median_BuildingArea = Data['BuildingArea'].median()
Data_median_fill = Data.fillna({'BuildingArea':median_BuildingArea})
print("Dataframe after filling missing 'BuildingArea' with median:")
print(Data_median_fill)

Dataframe after filling missing 'BuildingArea' with median:
              Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S
2         Abbotsford      5 Charles St      3    h  1465000.0     SP
3         Abbotsford  40 Federation La      3    h   850000.0     PI
4         Abbotsford       55a Park St      4    h  1600000.0     VB
...              ...               ...    ...  ...        ...    ...
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP
13577   Williamstown       83 Power St      3    h  1170000.0      S
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0
...         ...         ...       ...       ...  ...       ...  ...       ...
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0             126.0        NaN        Yarra -37.79960   144.99840
1              79.0     1900.0        Yarra -37.80790   144.99340
2             150.0     1900.0        Yarra -37.80930   144.99440
3             126.0        NaN        Yarra -37.79690   144.99690
4             142.0     2014.0        Yarra -37.80720   144.99410
...             ...        ...          ...       ...         ...
13575         126.0     1981.0          NaN -37.90562   145.16761
13576         133.0     1995.0          NaN -37.85927   144.87904
13577         126.0     1997.0          NaN -37.85274   144.88738
13578         157.0     1920.0          NaN -37.85908   144.89299
13579         112.0     1920.0          NaN -37.81188   144.88449

                       Regionname Propertycount
0           Northern Metropolitan        4019.0
1           Northern Metropolitan        4019.0
2           Northern Metropolitan        4019.0
3           Northern Metropolitan        4019.0
4           Northern Metropolitan        4019.0
...                           ...           ...
13575  South-Eastern Metropolitan        7392.0
13576        Western Metropolitan        6380.0
13577        Western Metropolitan        6380.0
13578        Western Metropolitan        6380.0
13579        Western Metropolitan        6543.0

[13580 rows x 21 columns]

In [50]:
missingvalues_cnt = Data.isnull().sum()
print(missingvalues_cnt)

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
Price_range         0
dtype: int64

In [52]:
Data_specific_fill = Data.fillna({'CouncilArea':'Unknown'})
print("Dataframe after filling missing 'CouncilArea' with 'Unknown':")
print(Data_specific_fill)

Dataframe after filling missing 'CouncilArea' with 'Unknown':
              Suburb           Address  Rooms Type     Price Method   SellerG  \
0         Abbotsford      85 Turner St      2    h  0.632448      S    Biggin
1         Abbotsford   25 Bloomburg St      2    h -0.063640      S    Biggin
2         Abbotsford      5 Charles St      3    h  0.608984     SP    Biggin
3         Abbotsford  40 Federation La      3    h -0.353025     PI    Biggin
4         Abbotsford       55a Park St      4    h  0.820157     VB    Nelson
...              ...               ...    ...  ...       ...    ...       ...
13575  Wheelers Hill      12 Strada Cr      4    h  0.264851      S     Barry
13576   Williamstown     77 Merrett Dr      3    h -0.069897     SP  Williams
13577   Williamstown       83 Power St      3    h  0.147533      S     Raine
13578   Williamstown      96 Verdon St      4    h  2.227975     PI   Sweeney
13579     Yarraville        6 Agnes St      4    h  0.327421     SP   Village

             Date  Distance  Postcode  ...  Car  Landsize  BuildingArea  \
0       3/12/2016       2.5    3067.0  ...  0.1     202.0           NaN
1       4/02/2016       2.5    3067.0  ...  0.0     156.0          79.0
2       4/03/2017       2.5    3067.0  ...  0.0     134.0         150.0
3       4/03/2017       2.5    3067.0  ...  0.1      94.0           NaN
4       4/06/2016       2.5    3067.0  ...  0.2     120.0         142.0
...           ...       ...       ...  ...  ...       ...           ...
13575  26/08/2017      16.7    3150.0  ...  0.2     652.0           NaN
13576  26/08/2017       6.8    3016.0  ...  0.2     333.0         133.0
13577  26/08/2017       6.8    3016.0  ...  0.4     436.0           NaN
13578  26/08/2017       6.8    3016.0  ...  0.5     866.0         157.0
13579  26/08/2017       6.3    3013.0  ...  0.1     362.0         112.0

       YearBuilt  CouncilArea  Lattitude Longtitude  \
0            NaN        Yarra  -37.79960  144.99840
1         1900.0        Yarra  -37.80790  144.99340
2         1900.0        Yarra  -37.80930  144.99440
3            NaN        Yarra  -37.79690  144.99690
4         2014.0        Yarra  -37.80720  144.99410
...          ...          ...        ...        ...
13575     1981.0      Unknown  -37.90562  145.16761
13576     1995.0      Unknown  -37.85927  144.87904
13577     1997.0      Unknown  -37.85274  144.88738
13578     1920.0      Unknown  -37.85908  144.89299
13579     1920.0      Unknown  -37.81188  144.88449

                       Regionname  Propertycount Price_range
0           Northern Metropolitan         4019.0       Cheap
1           Northern Metropolitan         4019.0       Cheap
2           Northern Metropolitan         4019.0       Cheap
3           Northern Metropolitan         4019.0       Cheap
4           Northern Metropolitan         4019.0       Cheap
...                           ...            ...         ...
13575  South-Eastern Metropolitan         7392.0       Cheap
13576        Western Metropolitan         6380.0       Cheap
13577        Western Metropolitan         6380.0       Cheap
13578        Western Metropolitan         6380.0      Medium
13579        Western Metropolitan         6543.0       Cheap

[13580 rows x 22 columns]

In [17]:
Data_ffill = Data.ffill()
print(Data_ffill)

              Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S
2         Abbotsford      5 Charles St      3    h  1465000.0     SP
3         Abbotsford  40 Federation La      3    h   850000.0     PI
4         Abbotsford       55a Park St      4    h  1600000.0     VB
...              ...               ...    ...  ...        ...    ...
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP
13577   Williamstown       83 Power St      3    h  1170000.0      S
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0
...         ...         ...       ...       ...  ...       ...  ...       ...
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0               NaN        NaN        Yarra -37.79960   144.99840
1              79.0     1900.0        Yarra -37.80790   144.99340
2             150.0     1900.0        Yarra -37.80930   144.99440
3             150.0     1900.0        Yarra -37.79690   144.99690
4             142.0     2014.0        Yarra -37.80720   144.99410
...             ...        ...          ...       ...         ...
13575         172.0     1981.0  Maribyrnong -37.90562   145.16761
13576         133.0     1995.0  Maribyrnong -37.85927   144.87904
13577         133.0     1997.0  Maribyrnong -37.85274   144.88738
13578         157.0     1920.0  Maribyrnong -37.85908   144.89299
13579         112.0     1920.0  Maribyrnong -37.81188   144.88449

                       Regionname Propertycount
0           Northern Metropolitan        4019.0
1           Northern Metropolitan        4019.0
2           Northern Metropolitan        4019.0
3           Northern Metropolitan        4019.0
4           Northern Metropolitan        4019.0
...                           ...           ...
13575  South-Eastern Metropolitan        7392.0
13576        Western Metropolitan        6380.0
13577        Western Metropolitan        6380.0
13578        Western Metropolitan        6380.0
13579        Western Metropolitan        6543.0

[13580 rows x 21 columns]

In [18]:
Data_bfill = Data.bfill()
print(Data_bfill)

              Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S
2         Abbotsford      5 Charles St      3    h  1465000.0     SP
3         Abbotsford  40 Federation La      3    h   850000.0     PI
4         Abbotsford       55a Park St      4    h  1600000.0     VB
...              ...               ...    ...  ...        ...    ...
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP
13577   Williamstown       83 Power St      3    h  1170000.0      S
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0
...         ...         ...       ...       ...  ...       ...  ...       ...
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0              79.0     1900.0        Yarra -37.79960   144.99840
1              79.0     1900.0        Yarra -37.80790   144.99340
2             150.0     1900.0        Yarra -37.80930   144.99440
3             142.0     2014.0        Yarra -37.79690   144.99690
4             142.0     2014.0        Yarra -37.80720   144.99410
...             ...        ...          ...       ...         ...
13575         133.0     1981.0          NaN -37.90562   145.16761
13576         133.0     1995.0          NaN -37.85927   144.87904
13577         157.0     1997.0          NaN -37.85274   144.88738
13578         157.0     1920.0          NaN -37.85908   144.89299
13579         112.0     1920.0          NaN -37.81188   144.88449

                       Regionname Propertycount
0           Northern Metropolitan        4019.0
1           Northern Metropolitan        4019.0
2           Northern Metropolitan        4019.0
3           Northern Metropolitan        4019.0
4           Northern Metropolitan        4019.0
...                           ...           ...
13575  South-Eastern Metropolitan        7392.0
13576        Western Metropolitan        6380.0
13577        Western Metropolitan        6380.0
13578        Western Metropolitan        6380.0
13579        Western Metropolitan        6543.0

[13580 rows x 21 columns]

Exercise 3:Data Transformation

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
Data['Car'] = scaler.fit_transform(Data[['Car']])
print(Data)

              Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S
2         Abbotsford      5 Charles St      3    h  1465000.0     SP
3         Abbotsford  40 Federation La      3    h   850000.0     PI
4         Abbotsford       55a Park St      4    h  1600000.0     VB
...              ...               ...    ...  ...        ...    ...
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP
13577   Williamstown       83 Power St      3    h  1170000.0      S
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  0.1     202.0
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.1      94.0
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  0.2     120.0
...         ...         ...       ...       ...  ...       ...  ...       ...
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  0.2     652.0
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  0.2     333.0
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  0.4     436.0
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  0.5     866.0
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  0.1     362.0

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0               NaN        NaN        Yarra -37.79960   144.99840
1              79.0     1900.0        Yarra -37.80790   144.99340
2             150.0     1900.0        Yarra -37.80930   144.99440
3               NaN        NaN        Yarra -37.79690   144.99690
4             142.0     2014.0        Yarra -37.80720   144.99410
...             ...        ...          ...       ...         ...
13575           NaN     1981.0          NaN -37.90562   145.16761
13576         133.0     1995.0          NaN -37.85927   144.87904
13577           NaN     1997.0          NaN -37.85274   144.88738
13578         157.0     1920.0          NaN -37.85908   144.89299
13579         112.0     1920.0          NaN -37.81188   144.88449

                       Regionname Propertycount
0           Northern Metropolitan        4019.0
1           Northern Metropolitan        4019.0
2           Northern Metropolitan        4019.0
3           Northern Metropolitan        4019.0
4           Northern Metropolitan        4019.0
...                           ...           ...
13575  South-Eastern Metropolitan        7392.0
13576        Western Metropolitan        6380.0
13577        Western Metropolitan        6380.0
13578        Western Metropolitan        6380.0
13579        Western Metropolitan        6543.0

[13580 rows x 21 columns]

In [21]:
from sklearn.preprocessing import StandardScaler
Data['Price'] = StandardScaler().fit_transform(Data[['Price']])
print(Data)

              Suburb           Address  Rooms Type     Price Method   SellerG  \
0         Abbotsford      85 Turner St      2    h  0.632448      S    Biggin
1         Abbotsford   25 Bloomburg St      2    h -0.063640      S    Biggin
2         Abbotsford      5 Charles St      3    h  0.608984     SP    Biggin
3         Abbotsford  40 Federation La      3    h -0.353025     PI    Biggin
4         Abbotsford       55a Park St      4    h  0.820157     VB    Nelson
...              ...               ...    ...  ...       ...    ...       ...
13575  Wheelers Hill      12 Strada Cr      4    h  0.264851      S     Barry
13576   Williamstown     77 Merrett Dr      3    h -0.069897     SP  Williams
13577   Williamstown       83 Power St      3    h  0.147533      S     Raine
13578   Williamstown      96 Verdon St      4    h  2.227975     PI   Sweeney
13579     Yarraville        6 Agnes St      4    h  0.327421     SP   Village

             Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0       3/12/2016       2.5    3067.0  ...       1.0  0.1     202.0
1       4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0
2       4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0
3       4/03/2017       2.5    3067.0  ...       2.0  0.1      94.0
4       4/06/2016       2.5    3067.0  ...       1.0  0.2     120.0
...           ...       ...       ...  ...       ...  ...       ...
13575  26/08/2017      16.7    3150.0  ...       2.0  0.2     652.0
13576  26/08/2017       6.8    3016.0  ...       2.0  0.2     333.0
13577  26/08/2017       6.8    3016.0  ...       2.0  0.4     436.0
13578  26/08/2017       6.8    3016.0  ...       1.0  0.5     866.0
13579  26/08/2017       6.3    3013.0  ...       1.0  0.1     362.0

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0               NaN        NaN        Yarra -37.79960   144.99840
1              79.0     1900.0        Yarra -37.80790   144.99340
2             150.0     1900.0        Yarra -37.80930   144.99440
3               NaN        NaN        Yarra -37.79690   144.99690
4             142.0     2014.0        Yarra -37.80720   144.99410
...             ...        ...          ...       ...         ...
13575           NaN     1981.0          NaN -37.90562   145.16761
13576         133.0     1995.0          NaN -37.85927   144.87904
13577           NaN     1997.0          NaN -37.85274   144.88738
13578         157.0     1920.0          NaN -37.85908   144.89299
13579         112.0     1920.0          NaN -37.81188   144.88449

                       Regionname Propertycount
0           Northern Metropolitan        4019.0
1           Northern Metropolitan        4019.0
2           Northern Metropolitan        4019.0
3           Northern Metropolitan        4019.0
4           Northern Metropolitan        4019.0
...                           ...           ...
13575  South-Eastern Metropolitan        7392.0
13576        Western Metropolitan        6380.0
13577        Western Metropolitan        6380.0
13578        Western Metropolitan        6380.0
13579        Western Metropolitan        6543.0

[13580 rows x 21 columns]

In [22]:
Data = pd.DataFrame(Data)
original_columns = Data.columns
Data_dummies = pd.get_dummies(Data ,columns = ['Regionname'])
new_columns = Data_dummies.columns.difference(original_columns)
new_Data_columns = Data_dummies[new_columns]
print(new_Data_columns)

       Regionname_Eastern Metropolitan  Regionname_Eastern Victoria  \
0                                False                        False
1                                False                        False
2                                False                        False
3                                False                        False
4                                False                        False
...                                ...                          ...
13575                            False                        False
13576                            False                        False
13577                            False                        False
13578                            False                        False
13579                            False                        False

       Regionname_Northern Metropolitan  Regionname_Northern Victoria  \
0                                  True                         False
1                                  True                         False
2                                  True                         False
3                                  True                         False
4                                  True                         False
...                                 ...                           ...
13575                             False                         False
13576                             False                         False
13577                             False                         False
13578                             False                         False
13579                             False                         False

       Regionname_South-Eastern Metropolitan  \
0                                      False
1                                      False
2                                      False
3                                      False
4                                      False
...                                      ...
13575                                   True
13576                                  False
13577                                  False
13578                                  False
13579                                  False

       Regionname_Southern Metropolitan  Regionname_Western Metropolitan  \
0                                 False                            False
1                                 False                            False
2                                 False                            False
3                                 False                            False
4                                 False                            False
...                                 ...                              ...
13575                             False                            False
13576                             False                             True
13577                             False                             True
13578                             False                             True
13579                             False                             True

       Regionname_Western Victoria
0                            False
1                            False
2                            False
3                            False
4                            False
...                            ...
13575                        False
13576                        False
13577                        False
13578                        False
13579                        False

[13580 rows x 8 columns]

In [23]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop = 'first', sparse_output = False)
encoded_array = encoder.fit_transform(Data[['Regionname']])
encoded_Data = pd.DataFrame(encoded_array, columns = encoder.get_feature_names_out(['Regionname']))
Data_encoded = pd.concat([Data,encoded_Data], axis = 1).drop(columns=['Regionname'])
print(Data_encoded)

              Suburb           Address  Rooms Type     Price Method   SellerG  \
0         Abbotsford      85 Turner St      2    h  0.632448      S    Biggin
1         Abbotsford   25 Bloomburg St      2    h -0.063640      S    Biggin
2         Abbotsford      5 Charles St      3    h  0.608984     SP    Biggin
3         Abbotsford  40 Federation La      3    h -0.353025     PI    Biggin
4         Abbotsford       55a Park St      4    h  0.820157     VB    Nelson
...              ...               ...    ...  ...       ...    ...       ...
13575  Wheelers Hill      12 Strada Cr      4    h  0.264851      S     Barry
13576   Williamstown     77 Merrett Dr      3    h -0.069897     SP  Williams
13577   Williamstown       83 Power St      3    h  0.147533      S     Raine
13578   Williamstown      96 Verdon St      4    h  2.227975     PI   Sweeney
13579     Yarraville        6 Agnes St      4    h  0.327421     SP   Village

             Date  Distance  Postcode  ...  Lattitude  Longtitude  \
0       3/12/2016       2.5    3067.0  ...  -37.79960   144.99840
1       4/02/2016       2.5    3067.0  ...  -37.80790   144.99340
2       4/03/2017       2.5    3067.0  ...  -37.80930   144.99440
3       4/03/2017       2.5    3067.0  ...  -37.79690   144.99690
4       4/06/2016       2.5    3067.0  ...  -37.80720   144.99410
...           ...       ...       ...  ...        ...         ...
13575  26/08/2017      16.7    3150.0  ...  -37.90562   145.16761
13576  26/08/2017       6.8    3016.0  ...  -37.85927   144.87904
13577  26/08/2017       6.8    3016.0  ...  -37.85274   144.88738
13578  26/08/2017       6.8    3016.0  ...  -37.85908   144.89299
13579  26/08/2017       6.3    3013.0  ...  -37.81188   144.88449

       Propertycount  Regionname_Eastern Victoria  \
0             4019.0                          0.0
1             4019.0                          0.0
2             4019.0                          0.0
3             4019.0                          0.0
4             4019.0                          0.0
...              ...                          ...
13575         7392.0                          0.0
13576         6380.0                          0.0
13577         6380.0                          0.0
13578         6380.0                          0.0
13579         6543.0                          0.0

       Regionname_Northern Metropolitan  Regionname_Northern Victoria  \
0                                   1.0                           0.0
1                                   1.0                           0.0
2                                   1.0                           0.0
3                                   1.0                           0.0
4                                   1.0                           0.0
...                                 ...                           ...
13575                               0.0                           0.0
13576                               0.0                           0.0
13577                               0.0                           0.0
13578                               0.0                           0.0
13579                               0.0                           0.0

      Regionname_South-Eastern Metropolitan  Regionname_Southern Metropolitan  \
0                                       0.0                               0.0
1                                       0.0                               0.0
2                                       0.0                               0.0
3                                       0.0                               0.0
4                                       0.0                               0.0
...                                     ...                               ...
13575                                   1.0                               0.0
13576                                   0.0                               0.0
13577                                   0.0                               0.0
13578                                   0.0                               0.0
13579                                   0.0                               0.0

       Regionname_Western Metropolitan  Regionname_Western Victoria
0                                  0.0                          0.0
1                                  0.0                          0.0
2                                  0.0                          0.0
3                                  0.0                          0.0
4                                  0.0                          0.0
...                                ...                          ...
13575                              0.0                          0.0
13576                              1.0                          0.0
13577                              1.0                          0.0
13578                              1.0                          0.0
13579                              1.0                          0.0

[13580 rows x 27 columns]

In [24]:
Data['Price_range']=pd.cut(Data['Price'],bins = 4,labels = ['Cheap','Medium','Expensive','Ridiculously expensive'],right = True)
new_binned_columns = Data[['Suburb','Price_range']]
print(new_binned_columns.head(20))
print(new_binned_columns.tail(20))

        Suburb Price_range
0   Abbotsford       Cheap
1   Abbotsford       Cheap
2   Abbotsford       Cheap
3   Abbotsford       Cheap
4   Abbotsford       Cheap
5   Abbotsford       Cheap
6   Abbotsford       Cheap
7   Abbotsford       Cheap
8   Abbotsford       Cheap
9   Abbotsford       Cheap
10  Abbotsford       Cheap
11  Abbotsford       Cheap
12  Abbotsford       Cheap
13  Abbotsford       Cheap
14  Abbotsford       Cheap
15  Abbotsford       Cheap
16  Abbotsford       Cheap
17  Abbotsford       Cheap
18  Abbotsford       Cheap
19  Abbotsford       Cheap
                  Suburb Price_range
13560  Templestowe Lower       Cheap
13561  Templestowe Lower       Cheap
13562          Thornbury       Cheap
13563          Thornbury       Cheap
13564        Tullamarine       Cheap
13565            Vermont       Cheap
13566      Vermont South       Cheap
13567           Viewbank       Cheap
13568           Wantirna       Cheap
13569     Wantirna South       Cheap
13570     Wantirna South       Cheap
13571     Wantirna South       Cheap
13572           Watsonia       Cheap
13573           Werribee       Cheap
13574        Westmeadows       Cheap
13575      Wheelers Hill       Cheap
13576       Williamstown       Cheap
13577       Williamstown       Cheap
13578       Williamstown      Medium
13579         Yarraville       Cheap